### ISSUE TITLE
exception don't Work

### ISSUE THREAD

**Issue by Alvarion** [ShadowNinja/name_restrictions#2]
Hi,

I try Your restriction mod and as default admin user name have "admin". These username is entered into minetest.conf as config: "name = admin", but I can't login using thist username ... exception don't work properly. 

Edit: #3

**Comment by Alvarion** [comment]
Second  problem: user guest can  login. Only users Guest[num] cant login. i Fix it by added lines to disallowed list:

````
local disallowed = {
	["^guest"] = msg_guest,
	["^guest[0-9]+"] = msg_guest,
	["^squeakecrafter"] = msg_guest,
	["^squeakecrafter[0-9]+"] = msg_guest,
	["adm[1il]n"] = msg_misleading,
	["[0o]wn[e3]r"]  = msg_misleading,
	["^[0-9]+$"] = "All-numeric usernames are disallowed on this server.",
}
````

**Comment by ShadowNinja** [comment]
The variants without numbers have to be manually entered, so they're not a problem.

**Comment by ShadowNinja** [comment]
75b96c7cf9083333ba7c7e3dbbbc24e3eb3c3e5e

**Comment by Alvarion** [comment]
ok.thx
